### ISSUE TITLE
ugps miss GPS quality parameters

### ISSUE THREAD

**Issue by zokl** [openwrt/ugps#2]
ugps does not provide information about GPS signal quality. This is very impractical because the user cannot know what accuracy he can count on. The basic quality parameters are the number of visible satellites and the HDOP (Dilution of precision). Both can be found in the $GPGGA report, which is already being processed.

This PR https://github.com/openwrt/ugps/pull/1 adds support for both of these. Please include it in all affected development branches.

**Comment by blogic** [comment]
@zokl please fold all 3 patches into one and add the text above as the description

**Comment by zokl** [comment]
> @zokl please fold all 3 patches into one and add the text above as the description

New PR is up: https://github.com/openwrt/ugps/pull/3

**Comment by zokl** [comment]
@blogic Is myPR #3 OK now?
